### PR TITLE
fibonacci  using recursion

### PR DESCRIPTION
**Pull request by Paras-Mayur**

### CODE REVIEW

**Review by sanatbali — CHANGES_REQUESTED** [review]
Please pull request same code on @pranitrathod same repo
He will do it!

**Comment by Paras-Mayur** [comment]
> Please pull request same code on @pranitrathod same repo He will do it!

ok thank you lets connect on linkedin 
www.linkedin.com/in/parasmayur

**Comment by sanatbali** [comment]
Just push there he will PR yours too,just like mine also follow @pranitrathod he will help you out!

**Comment by pranitrathod** [comment]
Sure @Paras-Mayur PR on my repo CodeWithMe!

**Comment by Paras-Mayur** [comment]
> Sure @Paras-Mayur PR on my repo CodeWithMe!

sure

**Comment by Paras-Mayur** [comment]
> Just push there he will PR yours too,just like mine also follow @pranitrathod he will help you out!

sure

**Pull request closed without merging**
